[harness]
harness-it-a18f31c2 ansible_host=10.50.10.10 template=test-harness-template-v4

[products]
product1-it-a18f31c2 ansible_host=10.50.10.11 product_key=product1 template=product1-template-2026-07-01
product2-it-a18f31c2 ansible_host=10.50.10.12 product_key=product2 template=product2-template-2026-07-01

[send_udp]
product1-it-a18f31c2

[receive_udp]
product2-it-a18f31c2

[receive_audio]
product1-it-a18f31c2
product2-it-a18f31c2

[web_ui]
product1-it-a18f31c2
